name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: configure dependencies
      run: sudo apt-get install -y libncurses5-dev libncursesw5-dev

    - uses: actions/checkout@v2
    - name: make
      run: make
